// Web/reactVersion/src/pages/InChannel/components/ToolBar.tsx
import { Button, Row, Space, Col } from 'dingtalk-design-desktop';
import { memo, useCallback, useEffect, useState } from 'react';
import { useRecoilState, useRecoilValue } from 'recoil';
import { client, constantConfig, currentUserInfo, globalFlag, localChannelInfo } from '~/store';
import styles from '../index.module.less';
import { Camera, Mic, Screen } from '~/components/Device';
import { useDevice } from '~/hooks/device';
import Icon from '~/components/Icon';
import Settings from './Settings';
import classNames from 'classnames';

interface IProps {
  onLeave: () => void;
}

const Index = (props: IProps) => {
  const { onLeave: _onLeave } = props;
  const { screenTrack } = useRecoilValue(localChannelInfo);
  const [{ hideToolBar }, setGlobalFlag] = useRecoilState(globalFlag);
  const rtcClient = useRecoilValue(client);
  const [showSetting, setShowSetting] = useState(false);
  const { isMobile } = useRecoilValue(constantConfig);
  const { channel, appId } = useRecoilValue(currentUserInfo);
  const { operateCamera, operateMic, operateScreen, cameraEnabled, micEnabled } = useDevice('in');
  const onLeave = useCallback(() => {
    _onLeave();
    rtcClient.leave();
  }, [rtcClient, _onLeave]);

  useEffect(() => {
    let timer: number = null;
    const hideAfterStill = () => {
      if (timer) clearTimeout(timer);
      setGlobalFlag((prev) => ({ ...prev, hideToolBar: false }));
      timer = window.setTimeout(() => {
        setGlobalFlag((prev) => ({ ...prev, hideToolBar: true }));
      }, 10000);
    }
    document.addEventListener('mousemove', hideAfterStill)
    return () => {
      document.removeEventListener('mousemove', hideAfterStill)
    }
  }, []);

  const toggleShowSettings = useCallback(() => {
    setShowSetting((prev) => !prev)
  }, [])

  return (
    <Row className={classNames(styles.toolBarWrap, hideToolBar ? styles.hideToolBar : '')}>
      <Row className={styles.confInfo} gutter={16}>
        <Col>
          <span>应用: </span>
          <span>{appId}</span>
        </Col>
        <Col>
          <span>频道: </span>
          <span>{channel}</span>
        </Col>
      </Row>
      <Space size={[0, 8]}>
        <Row className={styles.toolBtn} onClick={operateCamera}>
          <Camera />
          <span>{cameraEnabled ? '关摄像头' : '开摄像头'}</span>
        </Row>
        <Row className={styles.toolBtn} onClick={operateMic}>
          <Mic />
          <span>{micEnabled ? '静音' : '解除静音'}</span>
        </Row>
        {isMobile ? null : (
          <Row
            onClick={operateScreen}
            className={`${styles.toolBtn} ${screenTrack ? styles.stopShare : ''}`}
          >
            <Screen />
            <span>{screenTrack ? '结束共享' : '共享'}</span>
          </Row>
        )}
        <Row className={styles.toolBtn} onClick={toggleShowSettings}>
          <Icon type='iconicon_x_Settings' />
          <span style={{ marginTop: 4 }}>设置</span>
        </Row>
      </Space>
      <Button type="danger" onClick={onLeave}>
        离开
      </Button>
      {showSetting ? <Settings onClose={toggleShowSettings} /> : null}
    </Row>
  );
};

export default memo(Index);

// Electron/src/renderer/src/pages/InChannel/components/ToolBar.vue
<template>
  <Row :class="['toolBarWrap', globalFlag.immersive ? 'hideBar' : '']">
    <Row class="confInfo" :gutter="16">
      <Col>
        <span>应用: </span>
        <span>{{ currentUserInfo.appId }}</span>
      </Col>
      <Col>
        <span>频道: </span>
        <span>{{ currentUserInfo.channel }}</span>
      </Col>
    </Row>
    <Space :size="[0, 8]">
      <Row class="toolBtn" @click="operateCamera">
        <Camera />
        <span>{{ deviceInfo.cameraEnable ? '关摄像头' : '开摄像头' }}</span>
      </Row>
      <Row class="toolBtn" @click="operateMic">
        <Mic />
        <span>{{ deviceInfo.micEnable ? '静音' : '解除静音' }}</span>
      </Row>
      <Row
        :class="['toolBtn', { stopShare: channelInfo.screenTrack }]"
        @click="toggleShowShareSelector"
      >
        <Screen />
        <span>{{ channelInfo.screenTrack ? '结束共享' : '共享' }}</span>
      </Row>
      <Row class="toolBtn" @click="toggleShowSettings">
        <Icon type="icon-icon_x_Settings" />
        <span style="margin-top: 4px">设置</span>
      </Row>
    </Space>
    <Button type="primary" danger @click="onLeave">
      离开
    </Button>
    <Settings v-if="showSetting" :close="toggleShowSettings" />
    <ShareSelector v-if="showShareSelector" :close="toggleShowShareSelector" />
  </Row>
</template>
<script lang="ts" setup>
import { Button, Row, Space, Col } from 'ant-design-vue';
import {
  useClient,
  useCurrentUserInfo,
  useGlobalFlag,
  useChannelInfo,
  useDeviceInfo,
} from '~/store';
import { Camera, Mic, Screen } from '~/components/Device';
import { useDevice } from '~/hooks/device';
import Icon from '~/components/Icon';
import ShareSelector from './ShareSelector.vue';
import Settings from './Settings/index.vue';
import { onMounted, onUnmounted, ref, toRaw } from 'vue';

interface IProps {
  onLeave: () => void;
}
const props = defineProps<IProps>();
const channelInfo = useChannelInfo();
const deviceInfo = useDeviceInfo();
const globalFlag = useGlobalFlag();
const client = useClient();
const currentUserInfo = useCurrentUserInfo();
const showSetting = ref(false);
const showShareSelector = ref(false);
const { operateCamera, operateMic, operateScreen } = useDevice('in');

const onLeave = async () => {
  toRaw(client).leave();
  props.onLeave();
};

const timer = ref(0);

const hideAfterStill = () => {
  if (timer.value) clearTimeout(timer.value);
  globalFlag.$patch({ immersive: false });
  timer.value = window.setTimeout(() => {
    globalFlag.$patch({ immersive: true });
  }, 10000);
};

onMounted(() => {
  document.addEventListener('mousemove', hideAfterStill);
});

onUnmounted(() => {
  document.removeEventListener('mousemove', hideAfterStill);
});

const toggleShowShareSelector = () => {
  if (!channelInfo.screenTrack) {
    showShareSelector.value = !showShareSelector.value
  } else {
    if (channelInfo.publishedTracks.has(channelInfo.screenTrack.getTrackId())) {
      operateScreen()
    }
  }
}

const toggleShowSettings = () => {
  showSetting.value = !showSetting.value;
};
</script>
<style lang="less" scoped>
@import url('../index.module.less');
</style>
