// DingRTC/Web/src/pages/InChannel/components/ToolBar.tsx
import { Button, Row, Space, Col } from 'dingtalk-design-desktop';
import { memo, useCallback } from 'react';
import { useRecoilValue, useSetRecoilState } from 'recoil';
import { client, constantConfig, currentUserInfo, globalFlag, localChannelInfo } from '~/store';
import styles from '../index.module.less';
import { Camera, Mic, Screen } from '~/components/Device';
import { useDevice } from '~/hooks/device';
import Icon from '~/components/Icon';

interface IProps {
  onLeave: () => void;
}

const Index = (props: IProps) => {
  const { onLeave: _onLeave } = props;
  const { hideLog } = useRecoilValue(constantConfig);
  const { screenTrack } = useRecoilValue(localChannelInfo);
  const IClient = useRecoilValue(client);
  const setShowGlobalFlag = useSetRecoilState(globalFlag);
  const { isMobile, env } = useRecoilValue(constantConfig);
  const { channel, appId } = useRecoilValue(currentUserInfo);
  const { operateCamera, operateMic, operateScreen, cameraEnabled, micEnabled } = useDevice('in');
  const onLeave = useCallback(() => {
    _onLeave();
    IClient.leave();
  }, [IClient, _onLeave]);

  const onShowLog = useCallback(() => {
    setShowGlobalFlag((prev) => ({ ...prev, showLog: true }));
  }, []);
  return (
    <Row className={styles.toolBarWrap}>
      <Row className={styles.confInfo} gutter={16}>
        <Col>
          <span>应用: </span>
          <span>{appId}</span>
        </Col>
        <Col>
          <span>环境: </span>
          <span>{env}</span>
        </Col>
        <Col>
          <span>频道: </span>
          <span>{channel}</span>
        </Col>
      </Row>
      <Space size={[0, 8]}>
        <Row className={styles.toolBtn} onClick={operateCamera}>
          <Camera />
          <span>{cameraEnabled ? '关摄像头' : '开摄像头'}</span>
        </Row>
        <Row className={styles.toolBtn} onClick={operateMic}>
          <Mic />
          <span>{micEnabled ? '静音' : '解除静音'}</span>
        </Row>
        {isMobile ? null : (
          <Row
            onClick={operateScreen}
            className={`${styles.toolBtn} ${screenTrack ? styles.stopShare : ''}`}
          >
            <Screen />
            <span>{screenTrack ? '结束共享' : '共享'}</span>
          </Row>
        )}
        {!hideLog && !isMobile ? (
          <Row className={styles.toolBtn} onClick={onShowLog}>
            <Icon type="iconicon_XDS_Calendar" />
            <span style={{ marginTop: 4 }}>操作日志</span>
          </Row>
        ) : null}
      </Space>
      <Button type="danger" onClick={onLeave}>
        离开
      </Button>
    </Row>
  );
};

export default memo(Index);

// Web/vueVersion/src/pages/InChannel/components/ToolBar.vue
<template>
  <Row :class="['toolBarWrap', globalFlag.immersive ? 'hideBar' : '']">
    <Row class="confInfo" :gutter="16">
      <Col>
        <span>应用: </span>
        <span>{{ currentUserInfo.appId }}</span>
      </Col>
      <Col>
        <span>频道: </span>
        <span>{{ currentUserInfo.channel }}</span>
      </Col>
    </Row>
    <Space :size="[0, 8]">
      <Row class="toolBtn" @click="operateCamera">
        <Camera />
        <span>{{ deviceInfo.cameraEnable ? '关摄像头' : '开摄像头' }}</span>
      </Row>
      <Row class="toolBtn" @click="operateMic">
        <Mic />
        <span>{{ deviceInfo.micEnable ? '静音' : '解除静音' }}</span>
      </Row>
      <Row
        v-if="!globalFlag.isMobile"
        :class="['toolBtn', { stopShare: channelInfo.screenTrack }]"
        @click="operateScreen"
      >
        <Screen />
        <span>{{ channelInfo.screenTrack ? '结束共享' : '共享' }}</span>
      </Row>
      <Row class="toolBtn" @click="toggleShowSettings">
        <Icon type="icon-icon_x_Settings" />
        <span style="margin-top: 4px">设置</span>
      </Row>
    </Space>
    <Button type="primary" danger @click="onLeave">
      离开
    </Button>
    <Settings v-if="showSetting" :close="toggleShowSettings" />
  </Row>
</template>
<script lang="ts" setup>
import { Button, Row, Space, Col } from 'ant-design-vue';
import {
  useClient,
  useCurrentUserInfo,
  useGlobalFlag,
  useChannelInfo,
  useDeviceInfo,
} from '~/store';
import { Camera, Mic, Screen } from '~/components/Device';
import { useDevice } from '~/hooks/device';
import Icon from '~/components/Icon';
import Settings from './Settings/index.vue';
import { ref } from 'vue';

interface IProps {
  onLeave: () => void;
}
const props = defineProps<IProps>();
const channelInfo = useChannelInfo();
const deviceInfo = useDeviceInfo();
const globalFlag = useGlobalFlag();
const client = useClient();
const currentUserInfo = useCurrentUserInfo();
const showSetting = ref(false);
const { operateCamera, operateMic, operateScreen } = useDevice('in');

const onLeave = async () => {
  client.leave();
  props.onLeave();
};

const toggleShowSettings = () => {
  showSetting.value = !showSetting.value;
};
</script>
<style lang="less" scoped>
@import url('../index.module.less');
</style>
