// Web/vueVersion/src/pages/Welcome/components/Preview.vue
<template>
  <Row class="previewWrap">
    <PlayResumer v-if="cameraTrack" :track="cameraTrack" :container="refContainer.$el" />
    <Col ref="refContainer" :class="!deviceInfo.cameraEnable ? 'avatar' : 'camera'">
      <Avatar size="large">{{ userName }}</Avatar>
    </Col>
    <Row class="devices">
      <Col class="deviceColumn">
        <Camera :click="operateCamera" />
      </Col>
      <Divider type="vertical" />
      <Col class="deviceColumn">
        <Mic :click="operateMic" />
      </Col>
    </Row>
  </Row>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { Mic, Camera } from '~/components/Device';
import { Row, Col, Divider, Avatar } from 'ant-design-vue';
import PlayResumer from '~/components/PlayResumer/Resumer.vue';
import { useDevice } from '~/hooks/device';
import { useGlobalFlag, useCurrentUserInfo, useDeviceInfo } from '~/store';

const refContainer = ref(null);

// 状态管理
const cameraTrack = ref(null);


const { userName } = useCurrentUserInfo();
const globalFlag = useGlobalFlag()
const deviceInfo = useDeviceInfo()

// 设备操作
const { openMicAndCameraSameTime, operateCamera, operateMic } = useDevice('pre');
onMounted(async () => {
  const [track] = await openMicAndCameraSameTime();
  cameraTrack.value = track;
  if (cameraTrack.value && !(globalFlag.isIOS && globalFlag.isWeixin)) {
    cameraTrack.value.play(refContainer.value.$el, { fit: 'cover' });
  }
});
</script>

<style lang="less" scoped>
@import url('../index.module.less');
</style>

// Web/reactVersion/src/pages/Welcome/components/Preview.tsx
import { Row, Col, Divider, Avatar } from 'dingtalk-design-desktop';
import { memo, useEffect, useRef, useState } from 'react';
import styles from '../index.module.less';
import { Camera, Mic } from '~/components/Device';
import { useDevice } from '~/hooks/device';
import { useRecoilValue } from 'recoil';
import { currentUserInfo } from '~/store';
import { isIOS, isWeixin } from '~/utils/tools';
import PlayResumer from '~/components/PlayResumer';

const Preview = () => {
  const { cameraEnabled, openMicAndCameraSameTime, operateCamera, operateMic } = useDevice('pre');
  const { userName } = useRecoilValue(currentUserInfo);
  const ref = useRef(null);
  const [cameraTrack, setCameraTrack] = useState(null)

  useEffect(() => {
    openMicAndCameraSameTime().then(([track]) => {
      setCameraTrack(track);
    })
  }, []);

  useEffect(() => {
    if (cameraTrack && !(isIOS() && isWeixin())) {
      cameraTrack.play(ref.current, { fit: 'cover' });
    }
  }, [cameraTrack])

  return (
    <Row className={styles.previewWrap}>
      <PlayResumer track={cameraTrack} container={ref.current} />
      <Col ref={ref} className={!cameraEnabled ? styles.avatar : styles.camera}>
        <Avatar size="large">{userName}</Avatar>
      </Col>
      <Row className={styles.devices}>
        <Col span={11}>
          <Camera onClick={operateCamera} />
        </Col>
        <Col span={1}>
          <Divider type="vertical" />
        </Col>
        <Col span={11}>
          <Mic onClick={operateMic} />
        </Col>
      </Row>
    </Row>
  );
};

export default memo(Preview);
