// Web/vueVersion/src/pages/Welcome/index.vue
<template>
  <div class="wrap">
    <Title :level="5" class="demoTitle">DingRTC Demo</Title>
    <Button 
      :disabled="testing" 
      class="testNetwork" 
      @click="onTestNetwork"
    >
      {{ testing ? `请等待${ticktok}s` : '测试网络' }}
    </Button>
    <div class="main">
      <Preview />
      <Join />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
import { Typography, Button } from 'ant-design-vue';
import Preview from "./components/Preview.vue";
import Join from "./components/Join.vue";
import { startTestNetworkQuality } from "~/utils/networkQuality";

const { Title } = Typography;

// 状态管理
const testing = ref(false);
const ticktok = ref(15);

// 方法
const onTestNetwork = async () => {
  if (!testing.value) {
    testing.value = true;
    ticktok.value = 15;

    const intervalId = setInterval(() => {
      ticktok.value = Math.max(0, ticktok.value - 1);
    }, 1000);

    await startTestNetworkQuality();

    testing.value = false;
    clearInterval(intervalId);
  }
};
</script>

<style lang="less" scoped>
@import url('./index.module.less');
</style>

// DingRTC/Web/reactVersion/src/pages/Welcome/index.tsx
import Join from "./components/Join";
import Preview from "./components/Preview";
import styles from './index.module.less';
import { memo, useCallback, useState } from "react";
import { Row, Typography, Col, Button } from "dingtalk-design-desktop";
import { startTestNetworkQuality } from "~/utils/networkQuality";

const { Title } = Typography;

const Index = () => {
  const [testing, setTesting] = useState(false);
  const [ticktok, setTicktok] = useState(15);
  const onTestNetwork = useCallback(() => {
    setTesting(true);
    setTicktok(15);
    const interval = setInterval(() => {
      setTicktok((prev) => Math.max(0, prev - 1))
    }, 1000)
    startTestNetworkQuality().then(() => {
      setTesting(false);
      clearInterval(interval);
    })
  }, [])
  return (
    <Row className={styles.wrap}>
      <Title level={6} className={styles.demoTitle}>DingRTC Demo</Title>
      <Button disabled={testing} className={styles.testNetwork} onClick={onTestNetwork}>{!testing ? '测试网络' : `请等待${ticktok}s` }</Button>
      <Col className={styles.main}>
        <Preview />
        <Join />
      </Col>
    </Row>
  )
}

export default memo(Index);
