// Web/vueVersion/src/pages/InChannel/components/Settings/ScreenShare.vue
<template>
  <Row>
    <Form :model="formData" style="width: 100%" :label-col="{span: 4 }" label-align="left">
      <Divider orientation="left" plain>
        <Text>视频编码设置</Text>
      </Divider>
      <Form.Item label="分辨率" name="dimension">
        <Select v-model:value="formData.dimension" :options="videoDimensions.map((item)=> ({ label: item, value: item }))" />
      </Form.Item>
      <Form.Item label="帧率" name="frameRate">
        <Select v-model:value="formData.frameRate" :options="frameRates.map((item)=> ({ label: item, value: item }))" />
      </Form.Item>
      <Form.Item label="优化模式" name="optimizationMode">
        <Select
          @change="onModeChange"
          v-model:value="formData.optimizationMode"
          :options="optionzationModeList"
        />
      </Form.Item>
      <Form.Item label="最大码率" name="maxBitrate">
        <InputNumber v-model:value="formData.maxBitrate" placeholder="默认用分辨率、帧率计算" addon-after="Kbps" />
      </Form.Item>
      <Button class="apply" @click="updateEncoder">
        应用
      </Button>
    </Form>
  </Row>
</template>
<script setup lang="ts">
import { LocalVideoTrack } from 'dingrtc';
import {
  Row,
  Typography,
  Divider,
  Form,
  Select,
  InputNumber,
  Button,
  message,
} from 'ant-design-vue';
import { reactive } from 'vue';
import { useChannel } from '~/hooks/channel';
import { useDeviceInfo, useChannelInfo } from '~/store';
import { videoDimensions, frameRates, optionzationModeList,  } from '~/constants';

const props = defineProps(['close']);
const deviceInfo = useDeviceInfo();
const channelInfo = useChannelInfo();
const { Text } = Typography;

const formData = reactive({
  dimension: deviceInfo.screenDimension,
  screenDimension: deviceInfo.screenDimension,
  frameRate: deviceInfo.screenFrameRate,
  maxBitrate: deviceInfo.screenMaxBitrate,
  optimizationMode: deviceInfo.screenOptimization,
})

const { close } = props;
const { publish, unpublish } = useChannel();

const onModeChange = (value) => {
  if (channelInfo.cameraTrack) {
    deviceInfo.$patch({ screenOptimization: value })
  }
}

const updateEncoder = () => {
  const { dimension, frameRate, maxBitrate } = formData;
  const isScreenPublish = channelInfo.publishedTracks.has(channelInfo.screenTrack.getTrackId());

  const fn = () => {
    if (!channelInfo.screenTrack) {
      message.info('请先创建共享轨道');
      return;
    }
    channelInfo.screenTrack
      .setEncoderConfiguration({
        frameRate,
        dimension,
        maxBitrate,
        optimizationMode: formData.optimizationMode,
      })
      .then(() => {
        deviceInfo.$patch({
          screenMaxBitrate: channelInfo.screenTrack.getMaxBitrate(),
        });
        publish([channelInfo.screenTrack as LocalVideoTrack]).then(() => {
          message.info('调整编码参数并重新发布成功');
          close();
        });
      });
  };
  if (isScreenPublish) {
    unpublish([channelInfo.screenTrack as LocalVideoTrack]).then(() => {
      fn();
    });
  } else {
    fn();
  }
  deviceInfo.$patch({
    screenDimension: dimension,
    screenMaxBitrate: maxBitrate,
    screenFrameRate: frameRate,
  });
}
</script>
<style lang="less" scoped>
@import url('./index.module.less');
</style>

// Web/reactVersion/src/pages/InChannel/components/Settings/ScreenShare.tsx
import {
  Row,
  Typography,
  Divider,
  Form,
  Select,
  InputNumber,
  Button,
  Toast,
} from 'dingtalk-design-desktop';
import { memo } from 'react';
import styles from './index.module.less';
import { useLocalChannel } from '~/hooks/channel';
import { useRecoilState } from 'recoil';
import { deviceInfo } from '~/store';
import { useForm } from 'dingtalk-design-desktop/lib/form/Form';
import { isIOS } from '~/utils/tools';
  
  
const { Text } = Typography;
const videoDimensions = [
  'VD_120x120',
  'VD_160x120',
  'VD_180x180',
  'VD_240x180',
  'VD_320x180',
  'VD_240x240',
  'VD_320x240',
  'VD_424x240',
  'VD_360x360',
  'VD_480x360',
  'VD_640x360',
  'VD_480x480',
  'VD_640x480',
  'VD_840x480',
  'VD_960x540',
  'VD_960x720',
  'VD_1280x720',
  'VD_1920x1080',
];
  
if (isIOS()) {
  videoDimensions.pop();
}
  
const frameRates = [5, 10, 15, 20, 30];
  
  interface ISettingsProps {
    onClose: () => void;
  }
  
const Share = (props: ISettingsProps) => {
  const { onClose } = props;
  const [{ screenDimension, screenFrameRate }, setDeviceInfo] = useRecoilState(deviceInfo);
  const { screenTrack, publish, unpublish, publishedTracks } = useLocalChannel();
  
  const [form] = useForm();
  
  const updateEncoder = () => {
    const { dimension, frameRate, maxBitrate } = form.getFieldsValue();
    const isScreenPublish = publishedTracks.includes(screenTrack);
  
    const fn = () => {
      if (!screenTrack) {
        Toast.info('请先创建共享轨道');
        return;
      }
      screenTrack
        .setEncoderConfiguration({
          frameRate,
          dimension,
          maxBitrate,
        })
        .then(() => {
          setDeviceInfo((prev) => ({
            ...prev,
            screenMaxBitrate: screenTrack.getMaxBitrate(),
          }));
          publish([screenTrack]).then(() => {
            Toast.info('调整编码参数并重新发布成功');
            onClose();
          });
        });
    };
    if (isScreenPublish) {
      unpublish([screenTrack]).then(() => {
        fn();
      });
    } else {
      fn();
    }
    setDeviceInfo((prev) => ({
      ...prev,
      screenDimension: dimension,
      screenMaxBitrate: maxBitrate,
      screenFrameRate: frameRate,
    }));
  };
  return (
    <Row>
      <Form
        form={form}
        style={{ width: '100%' }}
        labelCol={{ span: 4 }}
        labelAlign="left"
        initialValues={{
          dimension: screenDimension,
          frameRate: screenFrameRate,
          maxBitrate: '',
        }}
      >
        <Divider orientation="left" plain>
          <Text>视频编码设置</Text>
        </Divider>
        <Form.Item label="分辨率" name="dimension">
          <Select options={videoDimensions.map((item) => ({ label: item, value: item }))} />
        </Form.Item>
        <Form.Item label="帧率" name="frameRate">
          <Select options={frameRates.map((item) => ({ label: item, value: item }))} />
        </Form.Item>
        <Form.Item label="最大码率" name="maxBitrate">
          <InputNumber placeholder="默认用分辨率、帧率计算" addonAfter={'Kbps'} />
        </Form.Item>
        <Button className={styles.apply} onClick={updateEncoder}>
            应用
        </Button>
      </Form>
    </Row>
  );
};
  
export default memo(Share);
