// Web/vueVersion/src/pages/InChannel/components/Settings/Video.vue
<template>
  <Row class="videoSetting">
    <div class="videoWrapper">
      <video ref="videoSettingRef" loop autoPlay playsInline webkit-playsinline :controls="false" muted />
    </div>
    <Form style="width: 100%" :label-col="{ span: 4 }" label-align="left" :model="formData">
      <Form.Item label="摄像头" name="cameraId">
        <Select
          v-model:value="formData.cameraId"
          :options="deviceInfo.cameraList.map((item) => ({ label: item.label, value: item.deviceId }))"
          @change="onCameraIdChange"
        />
      </Form.Item>
      <Divider orientation="left" plain>
        <Text>视频编码设置</Text>
      </Divider>
      <Form.Item label="分辨率" name="dimension">
        <Select
          v-model:value="formData.dimension"
          :options="videoDimensions.map((item) => ({ label: item, value: item }))"
        />
      </Form.Item>
      <Form.Item label="帧率" name="frameRate">
        <Select
          v-model:value="formData.frameRate"
          :options="frameRates.map((item) => ({ label: item, value: item }))"
        />
      </Form.Item>
      <Form.Item label="优化模式" name="optionzationMode">
        <Select
          @change="onModeChange"
          v-model:value="formData.optimizationMode"
          :options="optionzationModeList"
        />
      </Form.Item>
      <Form.Item label="最大码率" name="maxBitrate">
        <InputNumber
          v-model:value="formData.maxBitrate"
          placeholder="默认用分辨率、帧率计算"
          addon-after="Kbps"
        />
      </Form.Item>
      <Button class="apply" @click="updateEncoder"> 应用 </Button>
    </Form>
  </Row>
</template>
<script lang="ts" setup>
import { CameraVideoTrack } from 'dingrtc';
import {
  Row,
  Typography,
  Divider,
  Form,
  Select,
  InputNumber,
  Button,
  message,
} from 'ant-design-vue';
import { reactive, ref, watchEffect } from 'vue';
import { useChannel } from '~/hooks/channel';
import { useDeviceInfo, useChannelInfo } from '~/store';
import { videoDimensions, frameRates, optionzationModeList,  } from '~/constants';

const { Text } = Typography;

const props = defineProps(['close']);
const { close } = props;
const videoSettingRef = ref<HTMLVideoElement>();
const deviceInfo = useDeviceInfo();

const formData = reactive({
  cameraId: deviceInfo.cameraId,
  maxBitrate: deviceInfo.cameraMaxBitrate,
  dimension: deviceInfo.cameraDimension,
  frameRate: deviceInfo.cameraFrameRate,
  optimizationMode: deviceInfo.cameraOptimization,
});
const channelInfo = useChannelInfo();
const { publish, unpublish } = useChannel();

const onModeChange = (value) => {
  if (channelInfo.cameraTrack) {
    deviceInfo.$patch({ cameraOptimization: value })
  }
}

const onCameraIdChange = (value) => {
  if (channelInfo.cameraTrack) {
    channelInfo.cameraTrack.setDevice(value).then(() => {
      const track = channelInfo.cameraTrack.getMediaStreamTrack();
      videoSettingRef.value!.srcObject = new MediaStream([track]);
      videoSettingRef.value!.play();
    });
  }
};

watchEffect(() => {
  if (!channelInfo.cameraTrack || !videoSettingRef.value) return;
  const track = channelInfo.cameraTrack.getMediaStreamTrack();
  videoSettingRef.value.srcObject = new MediaStream([track]);
  videoSettingRef.value.play();
});

const updateEncoder = () => {
  const isCameraPublish = channelInfo.publishedTracks.has(channelInfo.cameraTrack.getTrackId());
  const fn = () => {
    if (!channelInfo.cameraTrack) {
      message.info('请先创建摄像头轨道');
      return;
    }
    channelInfo.cameraTrack
      .setEncoderConfiguration({
        frameRate: formData.frameRate,
        dimension: formData.dimension,
        optimizationMode: formData.optimizationMode,
        maxBitrate: Number(formData.maxBitrate),
      })
      .then(() => {
        deviceInfo.$patch({ cameraMaxBitrate: channelInfo.cameraTrack.getMaxBitrate() });
        publish([channelInfo.cameraTrack as CameraVideoTrack]).then(() => {
          message.info('调整编码参数并重新发布成功');
          close();
        });
      });
  };
  if (isCameraPublish) {
    unpublish([channelInfo.cameraTrack as CameraVideoTrack]).then(() => {
      fn();
    });
  } else {
    fn();
  }
  deviceInfo.$patch({
    cameraFrameRate: formData.frameRate,
    cameraDimension: formData.dimension,
    cameraMaxBitrate: Number(formData.maxBitrate),
  });
};
</script>
<style lang="less" scoped>
@import url('./index.module.less');
</style>

// Web/reactVersion/src/pages/InChannel/components/Settings/Video.tsx
import {
  Row,
  Typography,
  Divider,
  Form,
  Select,
  InputNumber,
  Button,
  Toast,
} from 'dingtalk-design-desktop';
import { memo, useCallback, useEffect, useRef } from 'react';
import styles from './index.module.less';
import { useLocalChannel } from '~/hooks/channel';
import { useRecoilState } from 'recoil';
import { deviceInfo } from '~/store';
import { useForm } from 'dingtalk-design-desktop/lib/form/Form';
import { isIOS } from '~/utils/tools';
  
  
const { Text } = Typography;
const videoDimensions = [
  'VD_120x120',
  'VD_160x120',
  'VD_180x180',
  'VD_240x180',
  'VD_320x180',
  'VD_240x240',
  'VD_320x240',
  'VD_424x240',
  'VD_360x360',
  'VD_480x360',
  'VD_640x360',
  'VD_480x480',
  'VD_640x480',
  'VD_840x480',
  'VD_960x540',
  'VD_960x720',
  'VD_1280x720',
  'VD_1920x1080',
];
  
if (isIOS()) {
  videoDimensions.pop();
}
  
const frameRates = [5, 10, 15, 20, 30];
  
  interface ISettingsProps {
    onClose: () => void;
  }
  
const Video = (props: ISettingsProps) => {
  const { onClose } = props;
  const videoRef = useRef<HTMLVideoElement>(null);
  const [{ cameraDimension, cameraFrameRate, cameraId, cameraList }, setDeviceInfo] =
      useRecoilState(deviceInfo);
  const { cameraTrack, publish, unpublish, publishedTracks } = useLocalChannel();
  const [form] = useForm();
  const onFieldsChange = useCallback(
    (changedFields: any[]) => {
      const [{ name, value }] = changedFields;
      if (name[0] === 'cameraId' && cameraTrack) {
        cameraTrack.setDevice(value).then(() => {
          const track = cameraTrack.getMediaStreamTrack();
          videoRef.current.srcObject = new MediaStream([track]);
          videoRef.current.play();
        });
      }
    },
    [cameraTrack],
  );
  
  useEffect(() => {
    if (!cameraTrack) return;
    const track = cameraTrack.getMediaStreamTrack();
    videoRef.current.srcObject = new MediaStream([track]);
    videoRef.current.play();
  }, [cameraTrack]);
  
  const updateEncoder = () => {
    const isCameraPublish = publishedTracks.includes(cameraTrack);
    const { dimension, frameRate, maxBitrate } = form.getFieldsValue();
    const fn = () => {
      if (!cameraTrack) {
        Toast.info('请先创建摄像头轨道');
        return;
      }
      cameraTrack
        .setEncoderConfiguration({
          frameRate,
          dimension,
          maxBitrate,
        })
        .then(() => {
          setDeviceInfo((prev) => ({
            ...prev,
            cameraMaxBitrate: cameraTrack.getMaxBitrate(),
          }));
          publish([cameraTrack]).then(() => {
            Toast.info('调整编码参数并重新发布成功');
            onClose();
          });
        });
    };
    if (isCameraPublish) {
      unpublish([cameraTrack]).then(() => {
        fn();
      });
    } else {
      fn();
    }
    setDeviceInfo((prev) => ({
      ...prev,
      cameraFrameRate: frameRate,
      cameraDimension: dimension,
      cameraMaxBitrate: maxBitrate,
    }));
  };
  
  return (
    <Row className={styles.videoSetting}>
      <div className={styles.videoWrapper}>
        <video loop autoPlay playsInline webkit-playsinline x5-playsinline controls={false} muted ref={videoRef} />
      </div>
      <Form
        form={form}
        onFieldsChange={onFieldsChange}
        style={{ width: '100%' }}
        labelCol={{ span: 4 }}
        labelAlign="left"
        initialValues={{
          cameraId,
          maxBitrate: '',
          dimension: cameraDimension,
          frameRate: cameraFrameRate,
        }}
      >
        <Form.Item label="摄像头" name="cameraId">
          <Select
            options={cameraList.map((item) => ({ label: item.label, value: item.deviceId }))}
          />
        </Form.Item>
        <Divider orientation="left" plain>
          <Text>视频编码设置</Text>
        </Divider>
        <Form.Item label="分辨率" name="dimension">
          <Select options={videoDimensions.map((item) => ({ label: item, value: item }))} />
        </Form.Item>
        <Form.Item label="帧率" name="frameRate">
          <Select options={frameRates.map((item) => ({ label: item, value: item }))} />
        </Form.Item>
        <Form.Item label="最大码率" name="maxBitrate">
          <InputNumber placeholder="默认用分辨率、帧率计算" addonAfter={'Kbps'} />
        </Form.Item>
        <Button className={styles.apply} onClick={updateEncoder}>
            应用
        </Button>
      </Form>
    </Row>
  );
};

export default memo(Video);
