// Electron/src/renderer/src/pages/InChannel/components/Settings/Video.vue
<template>
  <Row :key="componentKey" class="videoSetting">
    <div class="videoWrapper" ref="refContainer">
    </div>
    <Form style="width: 100%" :label-col="{ span: 4 }" label-align="left" :model="cameraFormData">
      <Form.Item label="摄像头" name="cameraId">
        <Select
          v-model:value="cameraFormData.cameraId"
          :options="
            deviceInfo.cameraList.map((item) => ({ label: item.label, value: item.deviceId }))
          "
          @change="onCameraIdChange"
        />
      </Form.Item>
    </Form>
    <Divider orientation="left" plain>
      <Text>摄像头编码设置</Text>
    </Divider>
    <Form style="width: 100%" label-align="left" layout="horizontal" :model="cameraFormData">
      <Row :gutter="24">
        <Col :span="12">
          <Form.Item label="分辨率" name="dimension">
            <Select
              v-model:value="cameraFormData.dimension"
              :options="videoDimensions.map((item) => ({ label: item, value: item }))"
            />
          </Form.Item>
        </Col>
        <Col :span="8">
          <Form.Item label="帧率" name="frameRate">
            <Select
              v-model:value="cameraFormData.frameRate"
              :options="frameRates.map((item) => ({ label: item, value: item }))"
            />
          </Form.Item>
        </Col>
        <Col :span="4">
          <Button class="apply" @click="updateCameraEncoder"> 应用 </Button>
        </Col>
      </Row>
    </Form>
    <Divider orientation="left" plain>
      <Text>虚拟背景设置</Text>
    </Divider>
    <Form style="width: 100%" label-align="left" layout="horizontal">
      <Row justify="space-between">
        <Col>
          <Form.Item label="背景图片">
            <Upload
              :max-count="1"
              :file-list="imageFileList"
              accept=".png"
              :before-upload="beforeUpload"
              @change="(changeParam) => onImageFileChange(changeParam)"
            >
              <Button> <UploadOutlined />选择背景图片</Button>
            </Upload>
          </Form.Item>
        </Col>
        <Col>
          <Form.Item>
            <Button @click="onBkImageApply">应用虚拟背景</Button>
          </Form.Item>
        </Col>
      </Row>
    </Form>
    <Divider orientation="left" plain>
      <Text>共享编码设置</Text>
    </Divider>
    <Form style="width: 100%" label-align="left" layout="horizontal" :model="shareFormData">
      <Row :gutter="24">
        <Col :span="12">
          <Form.Item label="分辨率" name="dimension">
            <Select
              v-model:value="shareFormData.dimension"
              :options="videoDimensions.map((item) => ({ label: item, value: item }))"
            />
          </Form.Item>
        </Col>
        <Col :span="8">
          <Form.Item label="帧率" name="frameRate">
            <Select
              v-model:value="shareFormData.frameRate"
              :options="frameRates.map((item) => ({ label: item, value: item }))"
            />
          </Form.Item>
        </Col>
        <Col :span="4">
          <Button class="apply" @click="updateShareEncoder"> 应用 </Button>
        </Col>
      </Row>
    </Form>
  </Row>
</template>
<script lang="ts" setup>
import {
  Row,
  Typography,
  Divider, Form,
  Select, Button,
  Upload,
  UploadFile,
  UploadChangeParam,
  message,
  Col
} from 'ant-design-vue';
import { webUtils } from 'electron';
import { UploadOutlined } from '@ant-design/icons-vue';
import { onBeforeUnmount, onMounted, reactive, ref, toRaw } from 'vue';
import { videoDimensions, frameRates } from '~/constants';
import { useChannel } from '~/hooks/channel';
import { useDeviceInfo, useChannelInfo } from '~/store';

import DingRTC, { CameraVideoTrack, LocalVideoTrack, VirtualBackgroundMode } from 'dingrtc-electron-sdk';

const componentKey = ref(0);
const imageFileList = ref<UploadFile[]>([]);
const imageFilePath = ref('');

const { Text } = Typography;

const props = defineProps(['close']);
const { close } = props;
const refContainer = ref(null);
const deviceInfo = useDeviceInfo();

const cameraFormData = reactive({
  cameraId: deviceInfo.cameraId,
  dimension: deviceInfo.cameraDimension,
  frameRate: deviceInfo.cameraFrameRate,
});

const shareFormData = reactive({
  dimension: deviceInfo.screenDimension,
  frameRate: deviceInfo.screenFrameRate,
})

onMounted(() => {
  toRaw(channelInfo.cameraTrack)?.play(refContainer.value);
})

onBeforeUnmount(() => {
    // @ts-ignore
    toRaw(channelInfo.cameraTrack)?.stop(refContainer.value);
})

const channelInfo = useChannelInfo();
const { publish } = useChannel();
const onCameraIdChange = (value) => {
  if (channelInfo.cameraTrack) {
    toRaw(channelInfo.cameraTrack).setDevice(value)
  }
};

const beforeUpload = () => false;
const onImageFileChange = async ({ fileList }: UploadChangeParam<any>) => {
  if (!fileList.length) return;
  const filePath = webUtils.getPathForFile(fileList[0].originFileObj);
  imageFileList.value = fileList;
  imageFilePath.value = filePath;
};

const updateCameraEncoder = () => {
  const { frameRate, dimension } = cameraFormData;
  const isCameraPublish = channelInfo.publishedTracks.has(channelInfo.cameraTrack?.getTrackId());
  if (!channelInfo.cameraTrack) {
    message.info('请先创建摄像头轨道');
    return;
  }
  toRaw(channelInfo.cameraTrack)
    .setEncoderConfiguration({
      frameRate,
      dimension,
    })
    .then(() => {
      if (!isCameraPublish) {
        publish([channelInfo.cameraTrack as CameraVideoTrack]).then(() => {
          message.info('调整编码参数并重新发布成功');
          close();
        });
      }
    });
  deviceInfo.$patch({
    cameraFrameRate: frameRate,
    cameraDimension: dimension,
  });
};


const updateShareEncoder = () => {
  const { dimension, frameRate } = shareFormData;
  const isScreenPublish = channelInfo.publishedTracks.has(channelInfo.screenTrack.getTrackId());

  if (!channelInfo.screenTrack) {
    message.info('请先创建共享轨道');
    return;
  }
  toRaw(channelInfo.screenTrack)
    .setEncoderConfiguration({
      frameRate,
      dimension,
    })
    .then(() => {
      if (!isScreenPublish) {
        publish([channelInfo.screenTrack as LocalVideoTrack]).then(() => {
          message.info('调整编码参数并重新发布成功');
          close();
        });
      }
    });
  deviceInfo.$patch({
    screenDimension: dimension,
    screenFrameRate: frameRate,
  });
}

const onBkImageApply = () => {
  DingRTC.enableVirtualBackground(true, {
    mode: VirtualBackgroundMode.VirtualBackgroundModeReplace,
    imagePath: imageFilePath.value
  });
}

</script>
<style lang="less" scoped>
@import url('./index.module.less');
</style>

// Web/reactVersion/src/pages/InChannel/components/Settings/Video.tsx
import {
  Row,
  Typography,
  Divider,
  Form,
  Select,
  InputNumber,
  Button,
  Toast,
} from 'dingtalk-design-desktop';
import { memo, useCallback, useEffect, useRef } from 'react';
import styles from './index.module.less';
import { useLocalChannel } from '~/hooks/channel';
import { useRecoilState } from 'recoil';
import { deviceInfo } from '~/store';
import { useForm } from 'dingtalk-design-desktop/lib/form/Form';
import { isIOS } from '~/utils/tools';
  
  
const { Text } = Typography;
const videoDimensions = [
  'VD_120x120',
  'VD_160x120',
  'VD_180x180',
  'VD_240x180',
  'VD_320x180',
  'VD_240x240',
  'VD_320x240',
  'VD_424x240',
  'VD_360x360',
  'VD_480x360',
  'VD_640x360',
  'VD_480x480',
  'VD_640x480',
  'VD_840x480',
  'VD_960x540',
  'VD_960x720',
  'VD_1280x720',
  'VD_1920x1080',
];
  
if (isIOS()) {
  videoDimensions.pop();
}
  
const frameRates = [5, 10, 15, 20, 30];
  
  interface ISettingsProps {
    onClose: () => void;
  }
  
const Video = (props: ISettingsProps) => {
  const { onClose } = props;
  const videoRef = useRef<HTMLVideoElement>(null);
  const [{ cameraDimension, cameraFrameRate, cameraId, cameraList }, setDeviceInfo] =
      useRecoilState(deviceInfo);
  const { cameraTrack, publish, unpublish, publishedTracks } = useLocalChannel();
  const [form] = useForm();
  const onFieldsChange = useCallback(
    (changedFields: any[]) => {
      const [{ name, value }] = changedFields;
      if (name[0] === 'cameraId' && cameraTrack) {
        cameraTrack.setDevice(value).then(() => {
          const track = cameraTrack.getMediaStreamTrack();
          videoRef.current.srcObject = new MediaStream([track]);
          videoRef.current.play();
        });
      }
    },
    [cameraTrack],
  );
  
  useEffect(() => {
    if (!cameraTrack) return;
    const track = cameraTrack.getMediaStreamTrack();
    videoRef.current.srcObject = new MediaStream([track]);
    videoRef.current.play();
  }, [cameraTrack]);
  
  const updateEncoder = () => {
    const isCameraPublish = publishedTracks.includes(cameraTrack);
    const { dimension, frameRate, maxBitrate } = form.getFieldsValue();
    const fn = () => {
      if (!cameraTrack) {
        Toast.info('请先创建摄像头轨道');
        return;
      }
      cameraTrack
        .setEncoderConfiguration({
          frameRate,
          dimension,
          maxBitrate,
        })
        .then(() => {
          setDeviceInfo((prev) => ({
            ...prev,
            cameraMaxBitrate: cameraTrack.getMaxBitrate(),
          }));
          publish([cameraTrack]).then(() => {
            Toast.info('调整编码参数并重新发布成功');
            onClose();
          });
        });
    };
    if (isCameraPublish) {
      unpublish([cameraTrack]).then(() => {
        fn();
      });
    } else {
      fn();
    }
    setDeviceInfo((prev) => ({
      ...prev,
      cameraFrameRate: frameRate,
      cameraDimension: dimension,
      cameraMaxBitrate: maxBitrate,
    }));
  };
  
  return (
    <Row className={styles.videoSetting}>
      <div className={styles.videoWrapper}>
        <video loop autoPlay playsInline webkit-playsinline x5-playsinline controls={false} muted ref={videoRef} />
      </div>
      <Form
        form={form}
        onFieldsChange={onFieldsChange}
        style={{ width: '100%' }}
        labelCol={{ span: 4 }}
        labelAlign="left"
        initialValues={{
          cameraId,
          maxBitrate: '',
          dimension: cameraDimension,
          frameRate: cameraFrameRate,
        }}
      >
        <Form.Item label="摄像头" name="cameraId">
          <Select
            options={cameraList.map((item) => ({ label: item.label, value: item.deviceId }))}
          />
        </Form.Item>
        <Divider orientation="left" plain>
          <Text>视频编码设置</Text>
        </Divider>
        <Form.Item label="分辨率" name="dimension">
          <Select options={videoDimensions.map((item) => ({ label: item, value: item }))} />
        </Form.Item>
        <Form.Item label="帧率" name="frameRate">
          <Select options={frameRates.map((item) => ({ label: item, value: item }))} />
        </Form.Item>
        <Form.Item label="最大码率" name="maxBitrate">
          <InputNumber placeholder="默认用分辨率、帧率计算" addonAfter={'Kbps'} />
        </Form.Item>
        <Button className={styles.apply} onClick={updateEncoder}>
            应用
        </Button>
      </Form>
    </Row>
  );
};

export default memo(Video);
