// Electron/src/renderer/src/pages/Welcome/index.vue
<template>
  <div class="wrap">
    <Title :level="5" class="demoTitle">DingRTC Demo</Title>
    <div class="main">
      <Preview />
      <Join />
    </div>
  </div>
</template>

<script setup lang="ts">
import { Typography } from 'ant-design-vue';
import Preview from "./components/Preview.vue";
import Join from "./components/Join.vue";

const { Title } = Typography;


</script>

<style lang="less" scoped>
@import url('./index.module.less');
</style>

// DingRTC/Web/src/pages/Welcome/index.tsx
import { memo } from "react";
import Join from "./components/Join";
import Preview from "./components/Preview";
import styles from './index.module.less';
import { Row, Typography, Col } from "dingtalk-design-desktop";

const { Title } = Typography;

const Index = () => {
  return (
    <Row className={styles.wrap}>
      <Title level={6} className={styles.demoTitle}>DingRTC Demo</Title>
      <Col className={styles.main}>
        <Preview />
        <Join />
      </Col>
    </Row>
  )
}

export default memo(Index);
