// Web/vueVersion/src/pages/InChannel/components/MainView.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { Tooltip, Row, Avatar } from 'ant-design-vue';
import { useGlobalFlag, useChannelInfo, useDeviceInfo, useCurrentUserInfo } from '~/store';
import Icon from '~/components/Icon';

const viewRef = ref(null);

// 状态管理
const globalFlag = useGlobalFlag();
const channelInfo = useChannelInfo();
const deviceInfo = useDeviceInfo();
const currentUserInfo = useCurrentUserInfo();

const micIconEnable = computed(() => {
  const isLocal = channelInfo.mainViewUserId === currentUserInfo.userId;
  if (isLocal) return deviceInfo.micEnable;
  return channelInfo.trackStatsMap.get(channelInfo.mainViewUserId)?.mic;
})


const videoIsPlay = computed(() => {
  const trackStats = channelInfo.trackStatsMap.get(channelInfo.mainViewUserId);
  return channelInfo.mainViewPreferType === 'auxiliary' ? trackStats?.screen : trackStats?.camera;
});

const showName = computed(() => channelInfo.mainViewUserInfo?.userName || currentUserInfo.userName)

watch(() => [viewRef.value, channelInfo.mainViewTrack], (newValue) => {
  if (newValue[1]) {
    newValue[1].play(viewRef.value.$el, {
      fit: 'contain',
    });
  }
})
</script>
<template>
  <Row ref="viewRef" :class="['mainView', { avatar: !videoIsPlay }]">
    <div v-if="channelInfo.mainViewTrack" :class="['smallViewStatus', { higherMainUserInfo: !globalFlag.immersive }]">
      <Icon v-if="channelInfo.trackStatsMap.get(channelInfo.mainViewUserId)?.screen" style="color: limegreen;" type="icon-XDS_share_screen1" />
      <Icon v-if="!micIconEnable" type="icon-XDS_UnMute2Fill" />
      <Tooltip :title="showName">
        <span>{{ showName }}</span>
      </Tooltip>
    </div>
    <Avatar size="large">
      {{ showName }}
    </Avatar>
  </Row>
</template>
<style lang="less" scoped>
@import url('../index.module.less');
</style>

// DingRTC/Web/reactVersion/src/pages/InChannel/components/MainView.tsx
import { Row, Tooltip } from "dingtalk-design-desktop"
import { memo, useEffect, useMemo, useRef } from "react"
import { useRecoilValue } from "recoil"
import { globalFlag, mainViewPrefer } from "~/store"
import styles from '../index.module.less';
import { useLocalChannel } from "~/hooks/channel";
import Icon from "~/components/Icon";
import classNames from "classnames";

const Index = () => {
  const { allUsers } = useLocalChannel();
  const { hideToolBar } = useRecoilValue(globalFlag);

  const mainPrefer = useRecoilValue(mainViewPrefer);
  const ref = useRef(null);

  const mainViewUserInfo = useMemo(() => allUsers.find(user => user.userId === mainPrefer.userId), [mainPrefer, allUsers]);

  const mainViewTrack = useMemo(() => {
    if (!mainViewUserInfo) return;
    return mainPrefer.prefer === 'camera' ? mainViewUserInfo.videoTrack : mainViewUserInfo.auxiliaryTrack;
  }, [mainPrefer, mainViewUserInfo]);

  const micIconEnable = useMemo(() => mainViewUserInfo?.hasAudio && !mainViewUserInfo?.audioMuted, [mainViewUserInfo]);

  useEffect(() => {
    if (mainViewTrack) {
      mainViewTrack?.play(ref.current, {
        fit: 'contain',
      });
    }
  }, [mainViewTrack])

  return (
    <Row ref={ref} className={styles.mainView}>
      {mainViewUserInfo ? <div className={classNames(styles.smallViewStatus, !hideToolBar ? styles.higherMainUserInfo : '')}>
        {mainViewUserInfo?.auxiliaryTrack ? (
          <Icon style={{ color: 'limegreen' }} type="iconXDS_share_screen1" />
        ) : !micIconEnable ? <Icon type="iconXDS_UnMute2Fill" /> : <Icon type="iconXDS_Mute2" />}
        <Tooltip title={mainViewUserInfo.userName}>
          <span>{mainViewUserInfo.userName}</span>
        </Tooltip>
      </div> : null}
    </Row>    
  )
}

export default memo(Index)
