// Web/vueVersion/src/pages/InChannel/components/SmallView.vue
<template>
  <Col
    ref="containerRef"
    :style="style"
    :class="[
      'smallVideoItem',
      {
        avatar: !videoIsPlay,
        camera: videoIsPlay,
        speaking: channelInfo.speakers.includes(user.userId),
      },
    ]"
    :span="span"
    @dblclick="viewBigger"
  >
    <span class="userId"> uid:{{ user.userId }} </span>
    <component
      :is="ScoreMap(channelInfo.remoteUserNetworkQualitys[user.userId] || 0)?.icon"
      v-if="!isLocal && track"
    />
    <Avatar size="large">
      {{ user.userName }}
    </Avatar>
    <div class="smallViewStatus">
      <Icon v-if="channelInfo.trackStatsMap.get(props.user.userId)?.screen" style="color: limegreen" type="icon-XDS_share_screen1" />
      <Icon v-if="!micIconEnable" type="icon-XDS_UnMute2Fill" />
      <Tooltip :title="user.userName">
        <span>{{ user.userName }}</span>
      </Tooltip>
    </div>
    <Tooltip :arrow="false" :overlay-inner-style="{ backgroundColor: 'rgba(245, 247, 250, 0.9)' }">
      <template #title>
        <List>
          <List.Item
            v-for="item in actions"
            :key="item.text"
            class="actionsItem"
            @click="item.onClick"
          >
            {{ item.text }}
          </List.Item>
        </List>
      </template>
      <div class="smallViewActions">
        <Icon type="icon-XDS_List" />
      </div>
    </Tooltip>
  </Col>
</template>
<script lang="ts" setup>
import { Avatar, Col, Tooltip, List } from 'ant-design-vue';
import Icon from '~/components/Icon';
import { downloadFileByBase64 } from '~/utils/tools';
import { useClient, useChannelInfo, useCurrentUserInfo, useDeviceInfo } from '~/store';
import { ScoreMap } from './NetworkBar';
import { computed, ref, watch } from 'vue';
import { useChannel } from '~/hooks/channel';


const props = defineProps(['user', 'span', 'style', 'track']);
const { subscribe, unsubscribe } = useChannel();
const user = ref(props.user);
const channelInfo = useChannelInfo();
const deviceInfo = useDeviceInfo();
const currentUserInfo = useCurrentUserInfo();
const client = useClient();
const streamType = ref(channelInfo.defaultRemoteStreamType);
const containerRef = ref(null);

const isLocal = computed(() => props.user.userId === currentUserInfo.userId);

const micIconEnable = computed(() => {
  if (isLocal.value) return deviceInfo.micEnable;
  return channelInfo.trackStatsMap.get(props.user.userId)?.mic;
})

const videoIsPlay = computed(() => {
  let track = props.track;
  const trackStats = channelInfo.trackStatsMap.get(props.user.userId);
  if (!track) return false;
  if (track === props.user.videoTrack) return trackStats?.camera;
  if (track === props.user.auxiliaryTrack) return trackStats?.screen;
  return false;
});


watch(() => [containerRef.value, props.track], (newValue) => {
  if (newValue[1]) {
    newValue[1].play(containerRef.value.$el, {
      fit: 'contain',
    });
  }
})

const viewBigger = () => {
  if (channelInfo.mode === 'grid') {
    channelInfo.mode = 'standard';
  }
  channelInfo.$patch((state) => {
    if (state.mainViewUserId === props.user.userId) {
      state.mainViewPreferType = state.mainViewPreferType === 'camera' ? 'auxiliary' : 'camera';
    } else {
      state.mainViewUserId = props.user.userId;
      state.mainViewPreferType = 'camera';
    }
  });
};

const actions = computed(() => {
  const uid = props.user.userId;
  const buttons = [
    {
      text: '截图',
      show: props.track,
      onClick: () => {
        downloadFileByBase64(props.track.getCurrentFrameData(), props.user.userId);
      },
    },
    {
      text: '订阅摄像头',
      show: !isLocal.value && channelInfo.trackStatsMap.get(uid)?.hasCamera && !channelInfo.trackStatsMap.get(uid)?.subscribedCamera,
      onClick: () => {
        subscribe(props.user, 'video');
      },
    },
    {
      text: '取消订阅摄像头',
      show: !isLocal.value && channelInfo.trackStatsMap.get(uid)?.subscribedCamera,
      onClick: () => {
        unsubscribe(props.user, 'video');
      },
    },
    {
      text: '订阅共享',
      show: !isLocal.value && channelInfo.trackStatsMap.get(uid)?.hasScreen && !channelInfo.trackStatsMap.get(uid)?.subscribedScreen,
      onClick: () => {
        subscribe(props.user, 'video', true);
      },
    },
    {
      text: '取消订阅共享',
      show: !isLocal.value && channelInfo.trackStatsMap.get(uid)?.subscribedScreen,
      onClick: () => {
        unsubscribe(props.user, 'video', true);
      },
    },
    {
      text: '切FHD',
      show: !isLocal.value && props.track && streamType.value !== 'FHD' && props.track === props.user.videoTrack,
      onClick: () => {
        client.setRemoteVideoStreamType(props.user.userId, 'FHD').then(() => {
          streamType.value = 'FHD';
        });
      },
    },
    {
      text: '切HD',
      show: !isLocal.value && props.track && streamType.value !== 'HD' && props.track === props.user.videoTrack,
      onClick: () => {
        client.setRemoteVideoStreamType(props.user.userId, 'HD').then(() => {
          streamType.value = 'HD';
        });
      },
    },
    {
      text: '切SD',
      show: !isLocal.value && props.track && streamType.value !== 'SD' && props.track === props.user.videoTrack,
      onClick: () => {
        client.setRemoteVideoStreamType(props.user.userId, 'SD').then(() => {
          streamType.value = 'SD';
        });
      },
    },
    {
      text: '切LD',
      show: !isLocal.value && props.track && streamType.value !== 'LD' && props.track === props.user.videoTrack,
      onClick: () => {
        client.setRemoteVideoStreamType(props.user.userId, 'LD').then(() => {
          streamType.value = 'LD';
        });
      },
    },
  ].filter((item) => item.show);
  return buttons;
});
</script>
<style lang="less" scoped>
@import url('../index.module.less');
</style>

// DingRTC/Web/reactVersion/src/pages/InChannel/components/SmallView.tsx
import { memo, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Avatar, Col, Tooltip, List, Modal } from 'dingtalk-design-desktop';
import Icon from '~/components/Icon';
import { RemoteUser } from 'dingrtc';
import { downloadFileByBase64, isIOS, isWeixin } from '~/utils/tools';
import styles from '../index.module.less';
import classNames from 'classnames';
import { useRemoteChannel } from '~/hooks/channel';
import { useDevice } from '~/hooks/device';
import { useRecoilState, useRecoilValue } from 'recoil';
import { client, mainViewPrefer } from '~/store';


interface UserItemProps {
  user: RemoteUser;
  isLocal: boolean;
}

const SmallView = memo((props: UserItemProps) => {
  const { user, isLocal } = props;
  const { speakers } = useRemoteChannel();
  const rtcClient = useRecoilValue(client);
  const [showActions, setShowActions] = useState(false);
  const [mainPrefer, setMainPrefer] = useRecoilState(mainViewPrefer);
  const { cameraEnabled, micEnabled } = useDevice();
  const [streamType, setStreamType] = useState('high');
  const ref = useRef<HTMLDivElement>(null);

  const micIconEnable = useMemo(() => {
    if (isLocal) return micEnabled;
    return user?.hasAudio && !user?.audioMuted;
  }, [isLocal, user?.hasAudio, user?.audioMuted, micEnabled]);

  const videoIsPlay = useMemo(() => {
    let track;
    if (mainPrefer.userId === user.userId) {
      track = mainPrefer.prefer === 'auxiliary' ? user.videoTrack : user.auxiliaryTrack
    } else {
      track = user.auxiliaryTrack || user.videoTrack;
    }
    if (!track) return false;
    if (track === user.videoTrack)
      return isLocal ? cameraEnabled : !user?.videoMuted;
    if (track === user.auxiliaryTrack)
      return isLocal || !user.auxiliaryMuted;
  }, [
    mainPrefer,
    user?.videoTrack?.isPlaying,
    isLocal,
    cameraEnabled,
    user?.videoMuted,
    user?.auxiliaryTrack,
    user?.auxiliaryMuted,
  ]);

  const playTrack = useCallback((track: any) => {
    Modal.centerConfirm({
      title: '提示',
      content: 'iOS微信浏览器需要在回调内播放',
      okText: '确认',
      onOk() {
        track.play(ref.current, { fit: 'cover' });
      },
      onCancel() {
        track.play(ref.current, { fit: 'cover' });
      }
    })
  }, []);

  const currentTrack = useMemo(() => {
    if (mainPrefer.userId === user.userId) {
      return mainPrefer.prefer === 'camera' ? user.auxiliaryTrack : user.videoTrack;
    }
    return user.auxiliaryTrack || user.videoTrack;
  }, [mainPrefer, user.videoTrack, user.auxiliaryTrack]);

  useEffect(() => {
    if (!currentTrack) return;
    if (isIOS() && isWeixin()) {
      playTrack(currentTrack);
    } else {
      currentTrack.play(ref.current, { fit: 'cover' });
    }
  }, [currentTrack]);

  const isCamera = useMemo(() => {
    const base = currentTrack && currentTrack === user.videoTrack;
    if (isLocal) return base && cameraEnabled;
    return base;
  }, [currentTrack, user.videoTrack, isLocal, cameraEnabled]);
  const isScreen = useMemo(
    () => currentTrack && currentTrack === user.auxiliaryTrack,
    [currentTrack, user.auxiliaryTrack],
  );

  const viewBigger = useCallback(() => {
    setMainPrefer((prev) => {
      if (prev.userId === user.userId) {
        return ({ userId: user.userId, prefer: prev.prefer === 'camera' ? 'auxiliary' : 'camera'})
      } else {
        return ({ userId: user.userId, prefer: 'camera' })
      }
    })
  }, [user, isScreen]);

  const wrapClass = classNames({
    [styles.smallVideoItem]: true,
    [styles.avatar]: !videoIsPlay,
    [styles.camera]: videoIsPlay,
    [styles.speaking]: speakers.includes(user.userId),
  });

  const Actions = useMemo(() => {
    const buttons = [
      {
        text: '截图',
        show: isCamera || isScreen,
        onClick: () => {
          let dataURL = '';
          if (isCamera) dataURL = user.videoTrack.getCurrentFrameData();
          if (isScreen) dataURL = user.auxiliaryTrack.getCurrentFrameData();
          downloadFileByBase64(dataURL, user.userId);
        },
      },
      {
        text: '切大流',
        show: !isLocal && isCamera && streamType === 'low',
        onClick: () => {
          rtcClient.setRemoteVideoStreamType(user.userId, 'high').then(() => {
            setStreamType('high');
          });
        },
      },
      {
        text: '切小流',
        show: !isLocal && isCamera && streamType === 'high',
        onClick: () => {
          rtcClient.setRemoteVideoStreamType(user.userId, 'low').then(() => {
            setStreamType('low');
          });
        },
      },
    ].filter((item) => item.show);
    if (!buttons.length) return null;
    return (
      <Tooltip
        trigger="click"
        overlayInnerStyle={{
          backgroundColor: 'rgba(245, 247, 250, 0.9)',
        }}
        open={showActions}
        onOpenChange={(show) => setShowActions(show)}
        title={
          <List>
            {buttons.map((item) => (
              <List.Item
                style={{ cursor: 'pointer' }}
                key={item.text}
                onClick={() => {
                  item.onClick();
                  setShowActions(false);
                }}
              >
                {item.text}
              </List.Item>
            ))}
          </List>
        }
      >
        <div className={styles.smallViewActions}>
          <Icon type="iconXDS_List" />
        </div>
      </Tooltip>
    );
  }, [
    isCamera,
    isScreen,
    isLocal,
    showActions,
    user?.videoTrack,
    user?.auxiliaryTrack,
    streamType,
    user?.hasAuxiliary,
    user?.hasVideo,
  ]);

  return (
    <Col ref={ref} onDoubleClick={viewBigger} className={wrapClass}>
      <span className={styles.userId} onClick={(e) => e.stopPropagation()}>
        uid:{user.userId}
      </span>
      <Avatar size="large">{user.userName}</Avatar>
      <div className={styles.smallViewStatus}>
        {user?.auxiliaryTrack ? (
          <Icon style={{ color: 'limegreen' }} type="iconXDS_share_screen1" />
        ) : !micIconEnable ? <Icon type="iconXDS_UnMute2Fill" /> : <Icon type="iconXDS_Mute2" />}
        <Tooltip title={user.userName}>
          <span>{user.userName}</span>
        </Tooltip>
      </div>
      {Actions}
    </Col>
  );
});

export default SmallView;
