// DingRTC/Web/reactVersion/src/pages/App/index.tsx
import InChannel from '../../pages/InChannel';
import { memo, useEffect } from 'react';
import { useRecoilValue } from 'recoil';
import { constantConfig, globalFlag } from '../../store';
import Welcome from '../../pages/Welcome';
import { Row, Toast, Modal } from 'dingtalk-design-desktop';
import styles from './index.module.less';
import DingRTC from 'dingrtc';
import { print } from '~/utils/tools';
import VConsole from 'vconsole';
import { useDevice } from '~/hooks/device';


const App = () => {
  const { joined } = useRecoilValue(globalFlag);
  const { updateDeviceList } = useDevice();
  const { hideLog, isMobile, isIOS, isWeixin } = useRecoilValue(constantConfig);
  useEffect(() => {
    if (!hideLog && isMobile) {
      // eslint-disable-next-line no-new
      new VConsole({});
    }
    print('start demo', navigator.userAgent);
    const supported = DingRTC.checkSystemRequirements();
    if (!supported) {
      Toast.error('当前浏览器不支持通话');
    }
    DingRTC.on('camera-changed', (info) => {
      updateDeviceList('camera', info);
    });
    DingRTC.on('microphone-changed', (info) => {
      updateDeviceList('microphone', info);
    });
    DingRTC.on('playback-device-changed', (info) => {
      updateDeviceList('playback-device', info);
    });
    DingRTC.on('autoplay-failed', (track) => {
      if (isIOS && isWeixin) {
        // @ts-ignore
        const wxBridge: any = window.WeixinJSBridge;
        print(wxBridge);
        if (wxBridge) {
          wxBridge.invoke('getNetworkType', {}, () => {
            print('autoTriggerPlay');
            track.play();
          });
        } else {
          document.addEventListener(
            'WeixinJSBridgeReady',
            () => {
              wxBridge.invoke('getNetworkType', {}, () => {
                print('autoTriggerPlay');
                track.play();
              });
            },
            false,
          );
        }
        return;
      }
      Modal.centerConfirm({
        content: '由于浏览器自动播放限制，点击确定后才会开始播放音频',
        onOk: () => {
          track.play();
        },
      });
    });
    return () => {
      DingRTC.removeAllListeners();
    };
  }, []);

  return (
    <Row className={styles.wrap}>
      {joined ? <InChannel /> : <Welcome />}
    </Row>
  );
};

export default memo(App);

// Web/vueVersion/src/pages/App/App.vue
<template>
  <div class="wrap">
    <template v-if="supported">
      <InChannel v-if="globalFlag.joined" />
      <Welcome v-else />
    </template>
  </div>
</template>

<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue";
import InChannel from "../InChannel/InChannel.vue";
import Welcome from "~/pages/Welcome/index.vue";
import { useGlobalFlag } from "~/store";
import { message, Modal } from 'ant-design-vue';
import DingRTC from "dingrtc";
import VConsole from "vconsole";
import { useDevice } from "~/hooks/device";
import 'ant-design-vue/dist/reset.css';


const globalFlag = useGlobalFlag();
const { updateDeviceList } = useDevice();
const supported = ref(false);


// 生命周期钩子
onMounted(() => {
  if (!globalFlag.hideLog && globalFlag.isMobile) {
    new VConsole();
  }

  const support = DingRTC.checkSystemRequirements();
  supported.value = support;
  if (!supported) {
    message.error("当前浏览器不支持通话");
  }

  DingRTC.on("camera-changed", (info) => {
    updateDeviceList("camera", info);
  });

  DingRTC.on("microphone-changed", (info) => {
    updateDeviceList("microphone", info);
  });

  DingRTC.on("playback-device-changed", (info) => {
    updateDeviceList("playback-device", info);
  });

  DingRTC.on("autoplay-failed", (track) => {
    Modal.centerConfirm({
      content: "由于浏览器自动播放限制，点击确定后才会开始播放音频",
      onOk() {
        // @ts-ignore
        track.play();
      },
    });
  });
});

onUnmounted(() => {
  DingRTC.removeAllListeners();
});
</script>

<style lang="less" scoped>
@import url("./index.module.less");
</style>
