// Web/reactVersion/src/pages/InChannel/index.tsx
import { memo, useCallback, useEffect, useState } from 'react';
import {
  RemoteUser,
  RemoteStreamType,
  TrackMediaType,
  NetworkQuality,
} from 'dingrtc';
import { Space, Row, Toast } from 'dingtalk-design-desktop';
import SmallView from './components/SmallView';
import { print, parseTime } from '~/utils/tools';
import { useRecoilState, useRecoilValue, useResetRecoilState, useSetRecoilState } from 'recoil';
import {
  client,
  globalFlag,
  localChannelInfo,
  mainViewPrefer,
  remoteChannelInfo,
} from '~/store';
import ToolBar from './components/ToolBar';
import styles from './index.module.less';
import { useLocalChannel, useNetworkStats, useRemoteChannel } from '~/hooks/channel';
import MainView from './components/MainView';
import { NetworkDetector } from './components/NetWorkBar/Networks';
import Icon from '~/components/Icon';

const Timer = memo(() => {
  const { timeLeft } = useRecoilValue(localChannelInfo);
  const [time, setTime] = useState(timeLeft - 1);
  useEffect(() => {
    const timer = setInterval(() => {
      setTime((currTime) => Math.max(currTime - 1, 0));
    }, 1000);
    return () => {
      clearInterval(timer);
    };
  }, []);
  return <span>剩余时长：{parseTime(time)}</span>;
});

const Index = memo(() => {
  const setGlobalFlag = useSetRecoilState(globalFlag);
  const rtcClient = useRecoilValue(client);
  const [fullscreen, setFullScreen] = useState(false);
  const { allUsers, cameraTrack, micTrack, screenTrack, timeLeft, setLocalChannelInfo, userId } = useLocalChannel();
  const { subscribe, unsubscribe, subscribeAllVideo } = useRemoteChannel();
  const resetLocalChannelInfo = useResetRecoilState(localChannelInfo);
  const resetMainViewPrefer = useResetRecoilState(mainViewPrefer);
  const setMainProfile = useSetRecoilState(mainViewPrefer);
  const resetRemoteChannelInfo = useResetRecoilState(remoteChannelInfo);
  const [{ remoteUsers, mcuAudioTrack }, setRemoteChannelInfo] = useRecoilState(remoteChannelInfo);
  const { getRtcStats, getRemoteUserNetworkStats } = useNetworkStats();

  const onFullScreen = useCallback(() => {
    if (!document.fullscreenElement) {
      setFullScreen(true);
      document.documentElement.requestFullscreen();
    } else if (document.exitFullscreen) {
      setFullScreen(false);
      document.exitFullscreen();
    }
  }, [])

  const clearRoom = useCallback(() => {
    if (cameraTrack) {
      cameraTrack.close();
    }
    if (document.fullscreenElement) {
      document.exitFullscreen();
    }
    if (micTrack) {
      micTrack.close();
    }
    if (screenTrack) {
      screenTrack.close();
    }
    if (mcuAudioTrack) {
      mcuAudioTrack.stop();
    }

    remoteUsers.forEach((user) => {
      if (user.auxiliaryTrack) {
        user.auxiliaryTrack.stop();
      }
      if (user.videoTrack) {
        user.videoTrack.stop();
      }
    });
    resetLocalChannelInfo();
    resetRemoteChannelInfo();
    resetMainViewPrefer();
    setGlobalFlag({
      joined: false,
      hideToolBar: false,
    });
  }, [mcuAudioTrack, remoteUsers, micTrack, cameraTrack, screenTrack, screenTrack, rtcClient]);
  useEffect(() => {
    rtcClient.on('user-joined', (user: RemoteUser) => {
      print(`user ${user.userId} joined`, user);
      setRemoteChannelInfo((prev) => ({ ...prev, remoteUsers: [...rtcClient.remoteUsers] }));
    });
    rtcClient.on('stream-type-changed', (uid: string, streamType: RemoteStreamType) => {
      print(`user ${uid} streamType changeTo ${streamType}`);
    });

    rtcClient.on('connection-state-change', (current, _, reason) => {
      print(`connection-state-change ${current} ${reason || ''}`);
      if (current === 'disconnected') {
        if (reason !== 'leave') {
          Toast.info(reason);
        }
        clearRoom();
      }
    });
    rtcClient.on('network-quality', (uplink: NetworkQuality, downlink: NetworkQuality) => {
      setLocalChannelInfo((prev) => ({ ...prev, networkQuality: Math.max(uplink, downlink) as NetworkQuality }));
    });
    rtcClient.on('volume-indicator', (uids: string[]) => {
      if (uids.length) {
        print(`${uids.join()} is speaking`);
      }
      setRemoteChannelInfo((prev) => ({ ...prev, speakers: uids }));
    });
    rtcClient.on('user-info-updated', (uid, msg) => {
      print(`user ${uid}: ${msg}`);
      setRemoteChannelInfo((prev) => ({ ...prev, remoteUsers: [...rtcClient.remoteUsers] }));
    });
    rtcClient.on('user-left', (user: RemoteUser) => {
      print(`user ${user.userId} left`);
      setMainProfile(prev => {
        if (prev.userId === user.userId) {
          return ({ userId: '', prefer: 'auxiliary' })
        }
        return prev;
      });
      setRemoteChannelInfo((prev) => ({ ...prev, remoteUsers: [...rtcClient.remoteUsers] }));
    });
    rtcClient.on('group-add', (group: any) => {
      print(`group add`, group);
      setRemoteChannelInfo((prev) => ({ ...prev, groups: [...rtcClient.groups] }));
    });
    rtcClient.on('group-remove', (group: any) => {
      print(`group remove`, group);
      setRemoteChannelInfo((prev) => ({ ...prev, groups: [...rtcClient.groups] }));
    });
    rtcClient.on('group-user-join', (groupId: any, user: any) => {
      print(`group-user-join`, groupId, user);
      setRemoteChannelInfo((prev) => ({ ...prev, groups: [...rtcClient.groups] }));
    });
    rtcClient.on('group-user-leave', (groupId: any, user: any) => {
      print(`group-user-leave`, groupId, user);
      console.log(rtcClient.groups);
      setRemoteChannelInfo((prev) => ({ ...prev, groups: [...rtcClient.groups] }));
    });
    const onExitFullScreen = () => {
      if (!document.fullscreenElement) setFullScreen(false);
    }
    document.addEventListener('fullscreenchange', onExitFullScreen);
    return () => {
      document.removeEventListener('fullscreenchange', onExitFullScreen);
      rtcClient.removeAllListeners();
    };
  }, []);

  useEffect(() => {
    const onUserPublished = (user: RemoteUser, mediaType: TrackMediaType, auxiliary: boolean) => {
      print(`user ${user.userId} ${user.id} published ${mediaType === 'audio' ? 'audio' : auxiliary ? 'screenShare' : mediaType}}`);
      setRemoteChannelInfo((prev) => ({ ...prev, remoteUsers: [...rtcClient.remoteUsers] }));
      if (mediaType !== 'video') {
        return;
      }
      if (subscribeAllVideo) {
        subscribe(user, 'video', auxiliary);
      }
    };
    const onUserUnpublished = (user: RemoteUser, mediaType: TrackMediaType, auxiliary: boolean) => {
      print(`user ${user.userId} unpublished ${mediaType === 'audio' ? 'audio' : auxiliary ? 'screenShare' : mediaType}}`);
      if (mediaType === 'video') {
        setMainProfile((prev) => {
          if (prev.userId === user.userId) {
            if ((auxiliary && prev.prefer === 'auxiliary') || (!auxiliary && prev.prefer === 'camera')) {
              return ({ userId: '', prefer: 'auxiliary' })
            }
          }
          return prev;
        })
      }
      setRemoteChannelInfo((prev) => ({ ...prev, remoteUsers: [...rtcClient.remoteUsers] }));
    };
    rtcClient.on('user-unpublished', onUserUnpublished);
    rtcClient.on('user-published', onUserPublished);
    return () => {
      rtcClient.off('user-unpublished', onUserUnpublished);
      rtcClient.off('user-published', onUserPublished);
    };
  }, [subscribeAllVideo, subscribe, unsubscribe]);

  useEffect(() => {
    if (!screenTrack) return;
    const clearTrack = () => {
      screenTrack.stop();
      rtcClient.unpublish(screenTrack);
      setLocalChannelInfo((prev) => ({ ...prev, screenTrack: null }));
    };
    screenTrack.on('track-ended', clearTrack);
    return () => {
      screenTrack.off('track-ended', clearTrack);
    };
  }, [screenTrack]);

  useEffect(() => {
    getRtcStats();
    getRemoteUserNetworkStats();
    const timer = setInterval(() => {
      getRtcStats();
      getRemoteUserNetworkStats();
    }, 2000);
    return () => {
      clearInterval(timer);
    };
  }, [getRtcStats]);

  return (
    <Row className={styles.blockWrapper}>
      <Row>
        {timeLeft ? <Timer /> : null}
        <NetworkDetector />
        <Row className={styles.fullscreen} onClick={onFullScreen}><Icon type={fullscreen ? 'iconXDS_Minimize' : 'iconXDS_FullScreen'} />{fullscreen ? '退出全屏' : '全屏'}</Row>
      </Row>
      <Space size={8} className={styles.smallVideoItems}>
        {allUsers.map((user) => (
          <SmallView
            isLocal={user.userId === userId}
            user={user as RemoteUser}
            key={user.userId}
          />
        ))}
      </Space>
      <MainView />
      <ToolBar onLeave={clearRoom} />
    </Row>
  );
});

export default memo(Index);

// Web/vueVersion/src/pages/InChannel/InChannel.vue
<script lang="ts" setup>
import { ref, onMounted, onUnmounted, computed, watch, watchEffect } from 'vue';
import SmallView from './components/SmallView.vue';
import MainView from './components/MainView.vue';
import ToolBar from './components/ToolBar.vue';
import { NetworkDetector } from './components/NetworkBar';
import Icon from '~/components/Icon';
import { useClient, useGlobalFlag, useChannelInfo, useCurrentUserInfo, useDeviceInfo } from '~/store';

import { useChannel, useNetworkStats } from '~/hooks/channel';
import { parseTime, print } from '~/utils/tools';
import { Divider, Col, message, Radio, RadioGroup, Row, Space, Tooltip } from 'ant-design-vue';
import { Group, GroupPropertyUpdateTypes, GroupUser, LocalVideoTrack, NetworkQuality } from 'dingrtc';

const rtcStatsTimer = ref(0);
const wrapRef = ref(null);
const timeLeftTimer = ref(0);
const fullscreen = ref(false);
const channelInfo = useChannelInfo();
const client = useClient();
const globalFlag = useGlobalFlag();
const deviceInfo = useDeviceInfo();
const currentUserInfo = useCurrentUserInfo();
const { subscribe, checkMainview } = useChannel();
const { getRtcStats, getRemoteUserNetworkStats } = useNetworkStats();
const timeLeft = ref(channelInfo.timeLeft - 1);
const gridHeight = ref(0);

const immersiveTimer = ref(0);

const hideAfterStill = () => {
  if (immersiveTimer.value) clearTimeout(immersiveTimer.value);
  globalFlag.$patch({ immersive: false });
  immersiveTimer.value = window.setTimeout(() => {
    globalFlag.$patch({ immersive: true });
  }, 10000);
};

const onFullScreen = () => {
  if (!document.fullscreenElement) {
    fullscreen.value = true;
    document.documentElement.requestFullscreen();
  } else if (document.exitFullscreen) {
    fullscreen.value = false;
    document.exitFullscreen();
  }
};

const onExitFullScreen = () => {
  if (!document.fullscreenElement) fullscreen.value = false;
};

const clearTrack = () => {
  channelInfo.screenTrack.stop();
  client.unpublish([channelInfo.screenTrack as LocalVideoTrack]);
  channelInfo.$patch({ screenTrack: null });
};

const clearRoom = () => {
  if (document.fullscreenElement) {
    document.exitFullscreen();
  }
  if (channelInfo.cameraTrack) {
    channelInfo.cameraTrack.close();
  }
  if (channelInfo.micTrack) {
    channelInfo.micTrack.close();
  }
  if (channelInfo.screenTrack) {
    channelInfo.screenTrack.close();
  }
  if (channelInfo.mcuAudioTrack) {
    channelInfo.mcuAudioTrack.stop();
  }

  channelInfo.remoteUsers.forEach((user) => {
    if (user.auxiliaryTrack) {
      user.auxiliaryTrack.stop();
    }
    if (user.videoTrack) {
      user.videoTrack.stop();
    }
  });
  deviceInfo.$reset();
  channelInfo.$reset();
  globalFlag.$reset();
};

onMounted(() => {
  getRtcStats();
  getRemoteUserNetworkStats();
  document.addEventListener('fullscreenchange', onExitFullScreen);
  rtcStatsTimer.value = window.setInterval(() => {
    getRtcStats();
    getRemoteUserNetworkStats();
  }, 2000);
  timeLeftTimer.value = window.setInterval(() => {
    timeLeft.value = Math.max(timeLeft.value - 1, 0);
  }, 1000);
  client.on('user-unpublished', (user, mediaType, auxiliary) => {
    print(
      `user ${user.userId} unpublished ${mediaType === 'audio' ? 'audio' : auxiliary ? 'screenShare' : mediaType}}`,
    );
    channelInfo.updateTrackStats(user.userId);
    channelInfo.$patch({ remoteUsers: client.remoteUsers });
  });
  client.on('user-published', (user, mediaType, auxiliary) => {
    print(
      `user ${user.userId} ${user.id} published ${mediaType === 'audio' ? 'audio' : auxiliary ? 'screenShare' : mediaType}}`,
    );
    channelInfo.updateTrackStats(user.userId);
    channelInfo.$patch({ remoteUsers: client.remoteUsers });
    if (mediaType !== 'video') {
      return;
    }
    if (channelInfo.subscribeAllVideo) {
      subscribe(user, 'video', auxiliary);
    }
  });
  client.on('user-joined', (user) => {
    print(`user ${user.userId} joined`, user);
    channelInfo.$patch({ remoteUsers: client.remoteUsers });
    channelInfo.updateTrackStats(user.userId);
  });
  client.on('stream-type-changed', (uid, streamType) => {
    print(`user ${uid} streamType changeTo ${streamType}`);
  });

  client.on('connection-state-change', (current, _, reason) => {
    print(`connection-state-change ${current} ${reason || ''}`);
    if (current === 'disconnected') {
      if (reason !== 'leave') {
        message.info(reason);
      }
      clearRoom();
    }
  });
  client.on('network-quality', (uplink, downlink) => {
    channelInfo.$patch({ networkQuality: Math.max(uplink, downlink) as NetworkQuality });
  });
  client.on('volume-indicator', (uids: string[]) => {
    if (uids.length) {
      print(`${uids.join()} is speaking`);
    }
    channelInfo.$patch({ speakers: uids });
  });
  client.on('user-info-updated', (uid, msg) => {
    print(`user ${uid}: ${msg}`);
    channelInfo.$patch({ remoteUsers: client.remoteUsers });
    channelInfo.updateTrackStats(uid);
  });
  client.on('user-left', (user) => {
    print(`user ${user.userId} left`);
    checkMainview(user);
    channelInfo.updateTrackStats(user.userId);
    channelInfo.$patch({ remoteUsers: client.remoteUsers });
  });
  client.on('group-add', (group: Group) => {
    print(`group add`, group);
    channelInfo.groups = client.groups;
  });
  client.on('group-remove', (group: Group) => {
    print(`group remove`, group);
    channelInfo.$patch({ groups: client.groups });
  });
  client.on('group-user-join', (groupId: string, user: GroupUser) => {
    print(`group-user-join`, groupId, user);
    channelInfo.$patch({ groups: client.groups });
  });
  client.on('group-user-leave', (groupId: string, user: GroupUser) => {
    print(`group-user-leave`, groupId, user);
    channelInfo.$patch({ groups: client.groups });
  });
  client.on('group-info-updated', (groupId: string, event: GroupPropertyUpdateTypes, value?: string) => {
    print(`group-info-updated`, groupId, event, value);
    channelInfo.$patch({ groups: client.groups });
  });
  document.addEventListener('mousemove', hideAfterStill);
});

watch(() => channelInfo.screenTrack, () => {
  channelInfo.updateTrackStats(currentUserInfo.userId);
}, {
  immediate: true
})

watchEffect((cleanUp) => {
  if (!channelInfo.screenTrack) return;
  channelInfo.screenTrack?.on('track-ended', clearTrack);
  cleanUp(() => {
    channelInfo.screenTrack?.off('track-ended', clearTrack);
  });
});

onUnmounted(() => {
  clearInterval(rtcStatsTimer.value);
  clearInterval(timeLeftTimer.value);
  clearTimeout(immersiveTimer.value);
  document.removeEventListener('mousemove', hideAfterStill);
  client.removeAllListeners();
  document.removeEventListener('fullscreenchange', onExitFullScreen);
});

const spanNum = computed(() => {
  const userCount = channelInfo.allUsers.length;
  if (userCount > 9) return 6;
  else if (userCount > 4) return 8;
  else if (userCount > 1) return 12;
  return 24;
});

watch(
  () => [wrapRef.value, channelInfo.allUsers],
  (newValue) => {
    let clientHeight = newValue[0].$el.clientHeight - 12;
    const userCount = newValue[1].length;
    if (userCount > 9) clientHeight = clientHeight / 4;
    else if (userCount > 4) clientHeight = clientHeight / 3;
    else if (userCount > 1) clientHeight = clientHeight / 2;
    gridHeight.value = clientHeight;
  },
);
</script>

<template>
  <Row class="blockWrapper" ref="wrapRef">
    <Row :class="globalFlag.immersive ? 'hideBar' : ''">
      <span v-if="channelInfo.timeLeft">剩余时长：{{ parseTime(timeLeft) }}</span>
      <NetworkDetector />
      <Row class="fullscreen">
        <Tooltip
          :arrow="false"
          placement="bottomLeft"
          overlayClassName="viewConfigContainer"
          :overlay-inner-style="{ backgroundColor: 'rgba(245, 247, 250, 0.9)' }"
        >
          <Col class="viewConfigHot">
            <Icon :type="channelInfo.mode === 'grid' ? 'icon-gallery_20' : 'icon-speaker_top_20'" />
            视图
          </Col>
          <template #title>
            <Row class="viewConfig">
              <RadioGroup v-model:value="channelInfo.mode">
                <Radio value="standard">
                  <Icon type="icon-speaker_top_20" />
                  标准
                </Radio>
                <Radio value="grid">
                  <Icon type="icon-gallery_20" />
                  宫格
                </Radio>
              </RadioGroup>
              <Divider />
              <Col @click="onFullScreen">
                {{ fullscreen ? '退出全屏' : '全屏' }}
              </Col>
            </Row>
          </template>
        </Tooltip>
        <Divider type="vertical" v-if="fullscreen"/>
        <Icon class="viewConfigHot" v-if="fullscreen" @click="onFullScreen" type="icon-XDS_Minimize" />
      </Row>
    </Row>
    <Space v-if="channelInfo.mode === 'standard'" :class="['smallVideoItems', channelInfo.mode]">
      <SmallView v-for="user in channelInfo.allUsers" :key="user.userId" :user="user" :track="channelInfo.getTrack(user)" />
    </Space>
    <Row v-else :class="['smallVideoItems', channelInfo.mode]">
      <SmallView
        v-for="user in channelInfo.allUsers"
        :span="spanNum"
        :style="{ height: gridHeight + 'px' }"
        :key="user.userId"
        :user="user"
        :track="channelInfo.getTrack(user)"
      />
    </Row>
    <MainView v-if="channelInfo.mode === 'standard'" />
    <ToolBar @leave="clearRoom" />
  </Row>
</template>

<style lang="less" scoped>
@import url('./index.module.less');
</style>
