// Electron/src/renderer/src/pages/Welcome/components/Preview.vue
<template>
  <Row class="previewWrap">
    <Col ref="refContainer" :class="!deviceInfo.cameraEnable ? 'avatar' : 'camera'">
      <Avatar size="large">{{ userName }}</Avatar>
    </Col>
    <Row class="devices">
      <Col class="deviceColumn">
        <Camera :click="operateCamera" />
      </Col>
      <Divider type="vertical" />
      <Col class="deviceColumn">
        <Mic :click="operateMic" />
      </Col>
    </Row>
  </Row>

</template>

<script setup lang="ts">
import { Row, Col, Divider, Avatar } from 'ant-design-vue';
import { ref, onMounted, toRaw } from 'vue';
import { Mic, Camera } from '~/components/Device';
import { useDevice } from '~/hooks/device';
import { useCurrentUserInfo, useDeviceInfo } from '~/store';
const refContainer = ref(null);

// 状态管理
const cameraTrack = ref(null);

const { userName } = useCurrentUserInfo();
const deviceInfo = useDeviceInfo();

// 设备操作
const { openMicAndCameraSameTime, operateCamera, operateMic } = useDevice('pre');
onMounted(async () => {
  const track = await openMicAndCameraSameTime();
  cameraTrack.value = track;
  if (cameraTrack.value) {
    toRaw(cameraTrack.value).play(refContainer.value.$el, { fit: 'cover' });
  }
});
</script>

<style lang="less" scoped>
@import url('../index.module.less');
</style>

// DingRTC/Web/src/pages/Welcome/components/Preview.tsx
import { Row, Col, Divider, Avatar } from 'dingtalk-design-desktop';
import { memo, useEffect, useRef } from 'react';
import styles from '../index.module.less';
import { Camera, Mic } from '~/components/Device';
import { useDevice } from '~/hooks/device';
import { useRecoilValue } from 'recoil';
import { currentUserInfo } from '~/store';

const Preview = () => {
  const { cameraEnabled, openMicAndCameraSameTime, operateCamera, operateMic } = useDevice('pre');
  const { userName } = useRecoilValue(currentUserInfo);
  const ref = useRef(null);

  useEffect(() => {
    openMicAndCameraSameTime().then(([track]) => {
      track.play(ref.current, { fit: 'cover' });
    })
  }, []);

  return (
    <Row className={styles.previewWrap}>
      <Col ref={ref} className={!cameraEnabled ? styles.avatar : styles.camera}>
        <Avatar size="large">{userName}</Avatar>
      </Col>
      <Row className={styles.devices}>
        <Col span={11}>
          <Camera onClick={operateCamera} />
        </Col>
        <Col span={1}>
          <Divider type="vertical" />
        </Col>
        <Col span={11}>
          <Mic onClick={operateMic} />
        </Col>
      </Row>
    </Row>
  );
};

export default memo(Preview);
